#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Sensor, in2,    pot2,           sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFollow,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           right,         tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port5,           rightFollow,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           arm,           tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	while(true){
		int pot1val = SensorValue(in1);
		int pot2val = SensorValue(in2);
	}


}

void armRotation(float angle){
	const int encPerRotation = 2450;
	int target =  encPerRotation * (angle / 360);
	int startPos = nMotorEncoder(arm);
	int correctIterations = 0;
	int goalIterations = 100;
	int kP = 1.0;
	while(correctIterations < goalIterations){
		int error = target - (startPos - nMotorEncoder(arm));
	}



}
