#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           right,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           rightFollow,   tmotorVex393, openLoop)
#pragma config(Motor,  port4,           left,          tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           leftFollow,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int l, int r) {
	motor[right] = r;
	motor[rightFollow] = r;
	motor[left] = l;
	motor[leftFollow] = l;
}

int max(int a, int b) {
	if (a>b) {
		return a;
	}
	return b;
}

int min(int a, int b) {
	if (a<b) {
		return a;
	}
	return b;
}

task main()
{
	int startLeft = 0;
	int startRight = 0;
	const int target = 255;
	int error = 0;
	const int kP = 50.0;
	const int threshold = 10;
	int change = 0;
	while (true) {
		//drive(vexRT[Ch3], vexRT[Ch2]);
	drive(127,127);
		if (vexRT[Btn8D]) {


			if (startLeft == 0){
				startLeft = nMotorEncoder(left);
				startRight = nMotorEncoder(right);
			}


			// turn 90
			error = target - (startRight - nMotorEncoder(right)) - (startLeft - nMotorEncoder(left));
			if (error < threshold) {
				error = 0;
			}
			change = min(max(kP * error,255), -255);
			drive(error, -error);

			} else if (startLeft!=0){
				startLeft = 0;
				startRight = 0;
		}
	}
}
