#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           leftFollow,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           right,         tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port5,           rightFollow,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void drive(int l, int r) {
	motor[right] = r;
	motor[rightFollow] = r;
	motor[left] = l;
	motor[leftFollow] = l;
}

int max(int a, int b) {
	if (a>b) {
		return a;
	}
	return b;
}

int min(int a, int b) {
	if (a<b) {
		return a;
	}
	return b;
}

int absolute(int x) {
	if (x < 0) {
		return -x;
	}
	return x;
}

void pDrive(int heading){
	float ENC_PER_INCH = 360. / (4.*3.14);
	const float kP = 1.4;
	const int threshold = 15;
	int target = ENC_PER_INCH * (heading);
	int startLeft = nMotorEncoder(left);
	int startRight = nMotorEncoder(right);
	int correct = 0;
	int iter = 0;
	const int ZERO_VELOCITY = 100;

	// the 'while' is here to ensure velocity = 0, so we don't drift too far.
	while (correct < ZERO_VELOCITY) {
		iter++;
		int errorRight = target + (startRight - nMotorEncoder(right));
		int errorLeft = target - (startLeft - nMotorEncoder(left));
		errorRight = max(min(kP * errorRight, 127), -127);
		errorLeft = max(min(kP * errorLeft, 127), -127);
		drive(errorLeft, errorRight*.65);
		if (absolute(errorLeft) < threshold && absolute(errorRight) < threshold) {
			correct++;
		} else {
			correct = 0;
		}
	}
}

void turnTo(float heading) {
	const int ENC_PER_ROTATION = 2450;
	const float kP = 1.5;
	const int threshold = 5;
	int target = ENC_PER_ROTATION * (heading / 360);
	int startLeft = nMotorEncoder(left);
	int startRight = nMotorEncoder(right);
	float error = 0;
	int correct = 0;
	int iter = 0;
	const int ZERO_VELOCITY = 50;
//	const int MAX_ITER = 1000;

	// the 'while' is here to ensure velocity = 0, so we don't drift too far.
	while (correct < ZERO_VELOCITY) {
		iter++;
		error = target - (startRight - nMotorEncoder(right)) - (startLeft - nMotorEncoder(left));
		error = max(min(kP * error, 64), -64);
		drive(error, -error);
		if (absolute(error) < threshold) {
			correct++;
		} else {
			correct = 0;
		}
	}
}

/*
typedef enum ArmHeights{
	kUp = 1,
} ArmHeights;
*/

enum Direction {
	kForward,
	kStop,
	kBackward,
	kNone,
};

Direction getInputDirection() {
	if (vexRT[Btn8U])
		return kForward;
	if (vexRT[Btn8D])
		return kBackward;
	if (vexRT[Btn8L])
		return kStop;
	return kNone;
}

task driveForwardWhenPressed() {
	while ((getInputDirection() == kNone) || (getInputDirection() == kForward)) {
		drive(127, 127);
	}
}

task driveBackwardWhenPressed() {
	while ((getInputDirection() == kNone) || (getInputDirection() == kBackward)) {
		drive(-127, -127);
	}
}

task stopWhenPressed() {
	while ((getInputDirection() == kNone) || (getInputDirection() == kStop)) {
		drive(0, 0);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{

//const int target = 1000;
	while (true) {
		pDrive(54);
		pDrive(-4);
		turnTo(26);
		pDrive(-32);
		turnTo(-43);
		pDrive(33);
		turnTo(12);
		pDrive(-30);
		turnTo(45);
		pDrive(45);
		turnTo(-40);
		pDrive(60);

		wait1Msec(500);
		wait1Msec(10000);
	}
}

task usercontrol()
{
	// User control code here, inside the loop
	int direction = (int)kNone;
	int currentDirection;

	while (true)
	{
		currentDirection = getInputDirection();
	  if (currentDirection != (int)kNone && currentDirection != direction) {
	  	direction = currentDirection;
	  	switch (direction) {
	  		case kForward:
	  			startTask(driveForwardWhenPressed);
	  			break;
	  		case kBackward:
	  			startTask(driveBackwardWhenPressed);
	  			break;
	  		case kStop:
	  			startTask(stopWhenPressed);
	  			break;
	  		default:
	  			break;
	  	}
	  }

	}
}
