#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Sensor, in2,    pot2,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limit,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFollow,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           right,         tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port5,           rightFollow,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

enum ArmTarget{
	kSilver,
	kGold,
	kBack,
	kNone
};

//Math Stuff
int max(int a, int b) {
	if (a>b) {
		return a;
	}
	return b;
}

int min(int a, int b) {
	if (a<b) {
		return a;
	}
	return b;
}

int absolute(int x) {
	if (x < 0) {
		return -x;
	}
	return x;
}

//Driving Controls
void drive(int l, int r) {
	motor[right] = r;
	motor[rightFollow] = r;
	motor[left] = l;
	motor[leftFollow] = l;
}

void pDrive(int heading){//input inches
	float ENC_PER_INCH = 360. / (4.*3.14);
	const float kP = 1.4;
	const int threshold = 15;
	int target = ENC_PER_INCH * (heading);
	int startLeft = nMotorEncoder(left);
	int startRight = nMotorEncoder(right);
	int correct = 0;
	int iter = 0;
	const int ZERO_VELOCITY = 100;

	// the 'while' is here to ensure velocity = 0, so we don't drift too far.
	while (correct < ZERO_VELOCITY) {
		iter++;
		int errorRight = target + (startRight - nMotorEncoder(right));
		int errorLeft = target - (startLeft - nMotorEncoder(left));
		errorRight = max(min(kP * errorRight, 127), -127);
		errorLeft = max(min(kP * errorLeft, 127), -127);
		drive(errorLeft, errorRight*.65);
		if (absolute(errorLeft) < threshold && absolute(errorRight) < threshold) {
			correct++;
			} else {
			correct = 0;
		}
	}
}

void turnTo(float heading) {
	const int ENC_PER_ROTATION = 2450;
	const float kP = 1.5;
	const int threshold = 5;
	int target = ENC_PER_ROTATION * (heading / 360);
	int startLeft = nMotorEncoder(left);
	int startRight = nMotorEncoder(right);
	float error = 0;
	int correct = 0;
	int iter = 0;
	const int ZERO_VELOCITY = 50;
	//	const int MAX_ITER = 1000;

	// the 'while' is here to ensure velocity = 0, so we don't drift too far.
	while (correct < ZERO_VELOCITY) {
		iter++;
		error = target - (startRight - nMotorEncoder(right)) - (startLeft - nMotorEncoder(left));
		error = max(min(kP * error, 64), -64);
		drive(error, -error);
		if (absolute(error) < threshold) {
			correct++;
			} else {
			correct = 0;
		}
	}
}

void armTo(int input){
	float kP = 0.4;
	float kGravP = 0.1;
	float kBackP = 0.2;
	int error1 = 0;
	int error2 = 0;
	int target = 0;
	int silverTarget = 200;
	int goldTarget = 800;
	int backTarget = 1100;
	int vertical = 2000;
	bool limitSpeed = false;
	int correctIterations = 0;
	int goal = 50;
	switch (input){
	case kSilver:
		target = silverTarget;
		break;
	case kGold:
		target = goldTarget;
		break;
	case kBack:
		target = backTarget;
		limitSpeed = true;
		break;
	}
	while(correctIterations < goal){

		error1 = SensorValue(pot1);
		error2 = SensorValue(pot2);
		float value = (error1 + error2)/2.0;
		float avgError = target - value;
		float gravityError = vertical - value;

		// speed will be relative to effect of gravity and offset from target
		float speed;

		//flip
		/*
		if (limitSpeed) {
			if (600 < avgError < 1200) { // first stage slowing
				speed *= kBackP;
				speed = max(min(speed, 30), -30);
			} else if (600 < avgError) { // second stage slowing
				speed *= kBackP * 0.8;
				speed = max(min(speed, 13), -13);
			}else{
				speed = kP * avgError;
			}
		} else*/
		// not flipping

			speed = kP * avgError;


		//speed += kGravP * gravityError;

		motor[arm1] = speed;
		motor[arm2] = speed;
		if(abs(avgError) < 100 ){
			correctIterations++;
		}else{
			correctIterations = 0;

		}

	}
}

void openClaw(){
	motor[claw] = 50;
	wait1Msec(100);
}

void closeClaw(){
	int button = SensorValue(limit);
	clearTimer(T1);
	while(button!=1 && time1[T1] < 800){
		motor[claw] = -60;
	}
}



ArmTarget getInputDirection() {
	if (vexRT[Btn8U])
		return kBack;
	if (vexRT[Btn8D])
		return kSilver;
	if (vexRT[Btn8L])
		return kGold;
	return kNone;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{

	//const int target = 1000;
	while (true) {
		/*
		pDrive(54);//input inches
		pDrive(-4);//input degrees
		turnTo(26);
		pDrive(-32);
		turnTo(-43);
		pDrive(33);
		turnTo(12);
		pDrive(-30);
		turnTo(45);
		pDrive(45);
		turnTo(-40);
		pDrive(60);

		wait1Msec(500);
		wait1Msec(10000);
		*/

		armTo(kSilver);


	}
}
task goldArm(){
	while (((getInputDirection() == kNone) || (getInputDirection() == kGold))) {
		armTo(kGold);
	}
	motor[arm1] = 0;
	motor[arm2] = 0;
}

task silverArm(){
	while (((getInputDirection() == kNone) || (getInputDirection() == kSilver))) {
		armTo(kSilver);
	}
	motor[arm1] = 0;
	motor[arm2] = 0;
}

task dumpArm(){
	while ( ((getInputDirection() == kNone) || (getInputDirection() == kBack))) {
		armTo(kBack);
	}
	motor[arm1] = 0;
	motor[arm2] = 0;
}


task usercontrol()
{
	// User control code here, inside the loop
	int direction = (int)kNone;
	int currentDirection;

	while (true)
	{
		currentDirection = getInputDirection();
		if (currentDirection != (int)kNone && currentDirection != direction) {
			direction = currentDirection;
			switch (direction) {
			case kGold:
				startTask(goldArm);
				break;
			case kSilver:
				startTask(silverArm);
				break;
			case kBack:
				startTask(dumpArm);
				break;
			default:
				break;
			}
		}
	}
}
