#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port4,           right,         tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port5,           rightFollow,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port2,           left,          tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFollow,    tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int l, int r) {
	motor[right] = r;
	motor[rightFollow] = r;
	motor[left] = l;
	motor[leftFollow] = l;
}

int max(int a, int b) {
	if (a>b) {
		return a;
	}
	return b;
}

int min(int a, int b) {
	if (a<b) {
		return a;
	}
	return b;
}

task main()
{
	int startLeft = 0;
	int startRight = 0;
	const int target = 600;
	int error = 0;
	const int kP = 10.0;
	const int threshold = 0;
	int change = 0;
	int correct = 0;
	while (true) {


		//drive(127,127);
		if (vexRT[Btn8D]) {


			if (startLeft == 0){
				startLeft = nMotorEncoder(left);
				startRight = nMotorEncoder(right);
			}


			// turn 90
			error = target - (startRight - nMotorEncoder(right)) - (startLeft - nMotorEncoder(left));
			if (error < threshold) {
				correct++;
				if (correct == 4) {
					error = 0;
				}
			} else {
				correct = 0;
			}
			change = min(max(kP * error,255), -255);
			drive(error, -error);

			} else {
			drive(vexRT[Ch3], vexRT[Ch2]);


			if (startLeft!=0){
				startLeft = 0;
				startRight = 0;
			}
		}

	}
}
